### ISSUE TITLE
A way for relay server to give frontend a bit more context

### ISSUE THREAD

**Issue by brogan89** [MidLevel/MLAPI.Relay#9]
As I'm working with getting the relay server up and running, I was thinking it could be good to have some extra messages sent to the frontend so the host/client can better understand what is happening on the relay server side. 

1. When a host creates a new room, a message can be sent to the frontend with the IP/Port the host is on as the relay server seems to be setting a random port each time a new room is made.
2. A error message to the client trying to connect to a room that doesn't exist.

From there front end can handle it however they please. 

I have started this kind of in [my fork](https://github.com/brogan89/MLAPI.Relay/commit/7a4820a5782106af1edd6325d56dd73a64d53283) with TODOs. However, I don't understand how the `room.Send()` method works, my netcode knowledge is novice.

Thanks

**Comment by TwoTenPvP** [comment]
1. This feature already exists. See here: https://github.com/MidLevel/MLAPI.Relay/blob/master/MLAPI.Relay.Transports/UnetRelayTransport.cs#L31

The reason the number is random is because your router asigns it a random external port (mapped to the internal one).

2. You are welcome to work on the robustness, I personally will not be doing more work on this project I'm afraid. But I am happy to look at PRs

**Comment by brogan89** [comment]
> 1. This feature already exists. See here: https://github.com/MidLevel/MLAPI.Relay/blob/master/MLAPI.Relay.Transports/UnetRelayTransport.cs#L31
> 
> The reason the number is random is because your router asigns it a random external port (mapped to the internal one).
> 
> 1. You are welcome to work on the robustness, I personally will not be doing more work on this project I'm afraid. But I am happy to look at PRs

Ah yep. I didn't release this was in Unity's version as well `RelayTransport.OnRemoteEndpointReported`. Which is perfect. Thanks 👌
